const strings = {
    en: {
        login: "Login",
        register: "Register",
        emailid: "Email Id",
        password: "Password",
        home: "Home",
        post: "Post",
        profile: "profile",
        logout: "Logout",
        createPost: "Create Post",
        select: "Select",
        title: "Title",
        tagName: "Tag Name",
        createTag: "Create Tag",
        role: "Role",
        userTags: "User Tags",
        updateProfile: "Update Profile",
        username: "Username",
        confirmPassword: "Confirm Password",
        next: "Next",
    },
    fr: {
        login: "Connexion",
        register: "S'inscrire",
        emailid: "Identifiant de messagerie",
        password: "Mot de passe",
        home: "Domicile",
        post: "Poster",
        profile: "Profil",
        logout: "Se déconnecter",
        createPost: "Créer un article",
        select: "Sélectionner",
        title: "Titre",
        tagName: "Nom de la balise",
        createTag: "Créer une balise",
        role: "Rôle",
        userTags: "Balises utilisateur",
        updateProfile: "Mettre à jour le profil",
        username: "Nom d'utilisateur",
        confirmPassword: "Confirmez le mot de passe",
        next: "Suivant"
    }
};

export default strings;